EtwTcp 
| where Provider == 'Microsoft-Windows-Kernel-Network' and EventId in (10, 11) 
| extend ProcessName = getprocessname(EventData.PID)
| extend DestinationIpAddress = EventData.daddr, DestinationPort = ntohs(EventData.dport) 
| extend Size = EventData.size 
| extend ProcessId = EventData.PID 
| summarize Packets = count(), Bytes = sum(Size) 
	by bin(TimeCreated, 1m), ProcessId, ProcessName, DestinationIpAddress, DestinationPort
  
