# This workflow will build a project and execute all unit tests in its solution

name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Path: Source\KqlTools.sln                    # Path to solution
      Project_Path: Source\RealTimeKql\RealTimeKql.csproj   # Path to project

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build project
    - name: Build project
      run: dotnet build $env:Project_Path

    # Execute all unit tests in solution
    - name: Execute unit tests
      run: dotnet test $env:Solution_Path